COMP: Fixed naming conflict with Microsoft ERROR
c:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\wingdi.h does '#define ERROR 0', causing Visual C++ error C2059: syntax error: 'constant'.